---
# nome do banco de dados da aplicacao
wp_mysql_db: mybase
# login a ser criado para a aplicacao
wp_mysql_user: admin
# senha a ser atribuida para o login da aplicacao
wp_mysql_password: alakazan123
